### ISSUE TITLE
USER STORY: User Profile Sign Up / Login (All Users)

### ISSUE THREAD

**Issue by TheRickyroy** [TheRickyroy/pixel-to-page#1]
As a _user_ I can _sign up or login_ so that _I can engage with full site functionality_. 

**Acceptance Criteria**
- [x] Users can access the registration / login page from all pages
- [x] Users can create an account with valid username, emails and password
- [x] Navigation links update to reflect login status of user 
- [x] User receives immediate feedback upon successful / failed sign up / login attempt
- [x] Registered users attain additional functionality upon login
