### ISSUE TITLE
USER STORY: Blog Categories (Admin)

### ISSUE THREAD

**Issue by TheRickyroy** [TheRickyroy/pixel-to-page#11]
As a _Site Admin_, I can _categorise my blog posts_ so that _I can feature specific posts as necessary_

**Acceptance Criteria**
- [x] Admin can assign appropriate categories to each blog posts
- [x] Admin can assign featured status to blog posts for automatic inclusion on home page
- [x] Admin can filter categories for appropriate featuring of content
