### ISSUE TITLE
USER STORY: Blog Content (User)

### ISSUE THREAD

**Issue by TheRickyroy** [TheRickyroy/pixel-to-page#13]
As a _user_, I can _read blog posts_ so that I can _engage with relevant content_.

**Acceptance Criteria**
- [x] User can access and read blog posts
- [x] User can eaily naviagte between blog posts
- [x] User has appropriate UX functionality for reading blog content

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Create a BlogPost model in blog/models.py to store blog post data

You can review changes in this commit: https://github.com/lkilu6456546/TheRickyroy-pixel-to-page-13/commit/27c3874662bf73dcb7cc3442a3c57543ade2ab89.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
