### ISSUE TITLE
USER STORY: User Profile Page

### ISSUE THREAD

**Issue by TheRickyroy** [TheRickyroy/pixel-to-page#2]
As a _Registered User_, I can _login to my profile page_ so that _I can update my details and see previous activity_

**Acceptance Criteria**
- [x] User can access their profile page once they have registered / logged in
- [x] Profile page is only accessible to registered users (navigation updates upon login)
- [x] User can see profile information (username, join date, email, posts, likes and comments)
- [x] User can update their profile information (username, email, password)
- [x] Confirmation alert is provided upon profile information changes
- [x] Immediate feedback is given upon profile information change success
- [ ] #72
- [ ] #73
- [ ] #74
