### ISSUE TITLE
USER STORY: Community Content (Registered Users)

### ISSUE THREAD

**Issue by TheRickyroy** [TheRickyroy/pixel-to-page#22]
As a _Registered User_, I can _upload my journal images_ so that _I can share my ideas with the community and engage in feedback and conversation_

**Acceptance Criteria**
- [ ] User can upload a post with image(s) to a community gallery
- [ ] User can give image(s) a title, description and 
- [ ] User can create and submit posts for approval
- [ ] User can edit / delete their content
- [ ] Confirmation alert is provided upon edit to prevent accidental changes 
- [ ] Confirmation alert is provided upon delete request to prevent accidental deletion
- [ ] Immediate feedback is given upon submission , edit or deletion of content
