### ISSUE TITLE
USER STORY: User Notifications

### ISSUE THREAD

**Issue by TheRickyroy** [TheRickyroy/pixel-to-page#3]
As a _Registered User_, I can _select notification preferences_ so that _I can be alerted about relevant content_

**Acceptance Criteria**
- [ ] User can assign notification preferences
- [ ] User can edit notification preferences
- [ ] User can remove notification preferences
- [ ] Users receives email notification based on saved preferences
