### ISSUE TITLE
USER STORY: Content Search Functionality (User)

### ISSUE THREAD

**Issue by TheRickyroy** [TheRickyroy/pixel-to-page#50]
As a _User_ I can _search the website_ so that _I can find specific content_. 

**Acceptance Criteria**
- [ ] User can easily locate search function
- [ ] User can search for specific blog posts by keyword
- [ ] Search function returns desired results
- [ ] Results listed link to relevant content
