### ISSUE TITLE
USER STORY: Toggle Theme

### ISSUE THREAD

**Issue by TheRickyroy** [TheRickyroy/pixel-to-page#6]
As a _User_, I can _toggle theme_ so that _I can have a more enjoyable experience_

**Acceptance Criteria**
- [ ] User can toggle theme to suit their desired preference
- [ ] Toggle is easily available on all pages and devices
- [ ] Light / Dark / Alt theme available
- [ ] Theme use WCAG compliant palette
